import { HealthHistory } from "../Types/types";

export const enfermedades_concurrentes = [
   {"alergia": "Alergia"}, 
   {"hipertension": "Hipertensión"},
   {"hipotension":"Hipotensión"},
   {"diabetes":"Diabetes"},
   {"cardiopatias":"Cardiopatias"},
   {"vasculopatias":"Vasculopatias"},
   {"reumatismos":"Reumatismos"},
   {"tiroides":"Tiroides"},
   {"respiratorias":"Respiratorias"},
   {"piel":"Piel"},
   {"venereas":"Venereas"},
   {"aparato_digestivo":"Aparato Digestivo"},
   {"higado":"Higado"},
   {"vias_biliares":"Vias Biliares"},
   {"fracturas":"Fracturas"},
   {"aparato_genitourinario":"Aparato Genitourinario"},
   {"incontinencia":"Incontinencia"},
   {"convulsiones":"Convulsiones"}];

export const sensopersepcion = [
   { "s_sin_alteracion": "Sin alteración"},
   { "ilusiones": "Ilusiones"},
   { "alucinaciones_visuales": "Alucinaciones visuales"},
   { "alucinaciones_auditivas": "Alucinaciones auditivas"},
   { "alucinaciones_cenestesicas": "Alucinaciones cenestesicas"},
   { "alucinaciones_terrorificas": "Alucinaciones terrorificas"},
   { "alucinaciones_placenteras_de_influencia": "Alucinaciones placenteras de influencia"},
   { "alucinaciones_diurnas": "Alucinaciones diurnas"},
   { "alucinaciones_nocturnas": "Alucinaciones nocturnas"},
   { "alucinaciones_aisladas": "Alucinaciones aisladas"},
   { "alucinaciones_permanentes": "Alucinaciones permanentes"},
   { "alucinaciones": "Alucinaciones"},
]

export const afectividad = [
   { "a_sin_alteracion": "Sin alteración"},
   { "hipertimia_placentera": "Hipertimia placentera"},
   { "hipomania": "Hipomania"},
   { "mania_franca": "Mania franca"},
   { "hipertimia_displacentera": "Hipertimia displacentera"},
   { "ansiedad_persecutoria": "Ansiedad persecutoria"},
   { "paratimia": "Paratimia"},
   { "indiferencia_afectiva": "Indiferencia afectiva"},
]

export const sueno = [
   { "normal": "Normal"},
   { "hipersomnia_diurnia": "Hipersomnia diurnia"},
   { "clinofilia": "Clinofilia"},
   { "hiposomnia_predormicional": "Hiposomnia predormicional"},
   { "hiposomnia_lacunaria": "Hiposomnia lacunaria"},
   { "hiposomnia_postdormicional": "Hiposomnia postdormicional"},
   { "sonambulismo": "Sonambulismo"},
   { "enuresis": "Enuresis"},
   { "pavor_nocturnus": "Pavor nocturnus"},
   { "deambulacion_nocturna": "Deambulación nocturna"},
]


export const defaultHealthHistory: HealthHistory = {
   id: 0,
   titulo: "",
   nro_documento: "",
   actitud_psiquica: "",
   actividad: "",
   afectividad: "",
   afiliado_nro: "",
   antecedentes_clinicos_y_quirurgicos: "",
   antecedentes_personales_personalidad_previa_escolaridad: "",
   aspecto_psiquico: "",
   atencion: "",
   conciencia: "",
   contenido_del_pensamiento: "",
   control_esfinteres: "",
   curso_del_pensamiento: "",
   diagnostico_cie10_dsm_iv: "",
   domicilio: "",
   domicilio_parentesco: "",
   edad: "",
   enfermedad_actual: "",
   enfermedades_concurrentes: "",
   esta_tomando_alguna_medicacion: "",
   estado_civil: "",
   evolucion: "",
   familiar_responsable_legal: "",
   fecha_ingreso: '1900-01-01',
   grupo_familiar_actual_antecedentes_familiares_vivienda: "",
   fecha_de_nacimiento: '1900-01-01',
   ideacion: "",
   inteligencia: "",
   juicio: "",
   lenguaje: "",
   memoria: "",
   motivo_de_consulta: "",
   nombre: "",
   obra_social: "",
   ocupacion_actual: "",
   ocupaciones_previas: "",
   orientacion: "",
   parentesco: "",
   sensopersepcion: "",
   sueno: "",
   telefono: "",
   telefono_parentesco: "",
   tipo_consulta: "",
   tratamientos_psiquiatricospsicologicos_previos: ""
 };  