export type HealthHistory = {
    id: number;
    titulo: string,
    nro_documento: string,
    actitud_psiquica: string,
    actividad: string,
    afectividad: string,
    afiliado_nro: string,
    antecedentes_clinicos_y_quirurgicos: string,
    antecedentes_personales_personalidad_previa_escolaridad: string,
    aspecto_psiquico: string,
    atencion: string,
    conciencia: string,
    contenido_del_pensamiento: string,
    control_esfinteres: string,
    curso_del_pensamiento: string,
    diagnostico_cie10_dsm_iv: string,
    domicilio: string,
    domicilio_parentesco: string,
    edad: string,
    enfermedad_actual: string,
    enfermedades_concurrentes: string,
    esta_tomando_alguna_medicacion: string,
    estado_civil: string,
    evolucion: string,
    familiar_responsable_legal: string,
    fecha_ingreso: string,
    grupo_familiar_actual_antecedentes_familiares_vivienda: string,
    fecha_de_nacimiento: string,
    ideacion: string,
    inteligencia: string,
    juicio: string,
    lenguaje: string,
    memoria: string,
    motivo_de_consulta: string,
    nombre: string,
    obra_social: string,
    ocupacion_actual: string,
    ocupaciones_previas: string,
    orientacion: string,
    parentesco: string,
    sensopersepcion: string,
    sueno: string,
    telefono: string,
    telefono_parentesco: string,
    tipo_consulta: string,
    tratamientos_psiquiatricospsicologicos_previos: string
}

export type historyChange = {
    id: number,
    healthHistoryId: number,
    changeDate: string,
    fieldName: string,
    oldValue: string,
    newValue: string
}